# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7499bf82012b5a2eb9f1bf42a6fd6f445b1ae5f419c7f2f6a18eae6c02460fe4c09f2c2ac552c37b33286fb84fcbb6881f5c437b095c42d808134d46e625d425

test:
  secret_key_base: 3bcac6f0ccccfc90d21bbbbc779cc41e74e79ff8cb902c5d4cfebbbc563079abdcd1c85764ee866c85a3b534a2a529b448ee92d48fd245954d8fc324d09f6f11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
